### ISSUE TITLE
Error when trying to use in plain javascript

### ISSUE THREAD

**Issue by jcotero** [Lusito/typed-signals#12]
Hello, I tried to use the module as a plain javascript. Here's the hellow world I was trying:

```
const { Signal, CollectorWhile0  } = require('typed-signals');

const PERIOD = 100; // 100 milliseconds

let mySignal = new Signal();
let collector = new CollectorWhile0(mySignal);

const myFunc = (s) => {
	console.log(s);
	setTimeout(() => { }, 20 * PERIOD); // awaits 20 * PERIOD milliseconds
	return true;
}

mySignal.connect(myFunc('Hello World'));

while (true) {
	collector.emit(); // calls signal.emit();
	while (!collector.getResult()) {
		setTimeout(() => { }, PERIOD); // awaits PERIOD milliseconds
	}
}
```

But I'm getting this error:
TypeError: link.callback.apply is not a function
at Signal.js:89:46
at Collector.js:19:37
at helloworld.js:17:12

Am I using it in the wrong way for plain javascript?

**Comment by jcotero** [comment]
Oh, I see my mistake... I should just call mySignal.connect(myFunc); and pass 'Hello World' in collector.emi('Hello World').
Now it's working fine.
